name: Update lockfile

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "**"

jobs:
  update-uv-lock:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Update lockfile
      run: |
        pip install uv
        uv sync
        uv lock

    - name: Commit formatted code
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update lockfile"
        commit_options: "--no-verify"
        repository: .
        commit_user_name: "github-actions[bot]"
        commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"